### ISSUE TITLE
Vertical scrollbar bounce when using a MacBook Pro(OS X Yosemite) and scrolling vertically up to the top of the page

### ISSUE THREAD

**Issue by damianChapman** [jstoudt/enscroll#61]
The scroll bar does not stay on the top of the page as expected but moves down slightly.
This does not happen when you scroll down to the bottom of the page. It also happens when tested on http://jsfiddle.net/jstoudt/PGuB5

**Comment by jstoudt** [comment]
@damianChapman, I'm sorry it took me so long to locate this bug. It turns out that when using the trackpad to scroll, a bunch of wheel events are generated by the browser and this series of events is then terminated with a wheel event having a delta of zero. This last wheel event was incorrectly interpreted by the plugin to be a scroll down wheel event.

I will be committing this change soon and will roll it into release 0.6.2.

**Comment by damianChapman** [comment]
Jason,

Thank you for getting back to me.

Regards,
Damian.

**Comment by jstoudt** [comment]
@damianChapman Version 0.6.2 has been released and can now be found at http://enscrollplugin.com/

**Comment by damianChapman** [comment]
Thanks Jason.
