### ISSUE TITLE
enscroll() not getting called from the js file :(

### ISSUE THREAD

**Issue by himanshuchaudhary** [jstoudt/enscroll#62]
$(document).ready(function() {
        console.log("Hi");
        $('.scrollbox').enscroll();
    });

Hi is getting printed but encroll(); not getting called.
Also... I am using the css class for ng-repeat.. and the values which are repeated are dynamic..

 <div class="scrollbox" >
                                        <div  ng-repeat="comment in service_Order.serviceOrderComments">
                                            <div class="comment-date">{{comment.commentsDate}} at {{comment.commentsTime}}</div>
                                            <div class="comment-section">
                                                <div class="comment" ng-init="commentLength=350">
                                                    {{comment.comments | limitTo:commentLength}} <a ng-show="commentLength==350 && comment.comments.length > 350" href ng-click="commentLength = comment.comments.length">...(Read more)</a>
                                                    <a ng-show="commentLength==comment.comments.length" href  ng-click="commentLength = 350">(Read less)</a></div>
                                            </div>
                                        </div>
                                    </div>

**Comment by jstoudt** [comment]
@himanshuchaudhary If you are using angular, angular loads a version of jQuery which may not have all the dependencies required by enscroll. If you load the full version of jQuery before angular, angular will use that version of jQuery instead of loading jqLite.

If this is true, you should be seeing something in the dev tool's console when calling enscroll as above.
